name: Clear File Contents

on:
  push:
    branches: [main]

jobs:
  clear-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clear specific files
      run: |
        find . -name "input.txt" -exec sh -c 'echo -n > "$1"' _ {} \;

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Clear contents of input.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}